### ISSUE TITLE
Not enough arguments!

### ISSUE THREAD

**Issue by ziceptor** [trentech/MysteryBlock#4]
`/mysteryblock add minecraft:...`

[pic](https://cloud.mail.ru/public/KrCk/eQXEgL5k6)

**Comment by trentech** [comment]
/mysteryblock &lt;block> &lt;name> &lt;percentage> &lt;type> &lt;data> [-a &lt;amplifier>] [-c]

&lt;block> Specifies to id of the BlockType
&lt;name> Specifies the new name of the event
&lt;percentage> The percent chance of triggering this event. Value should be 0-1
&lt;type> Specifies the event type. ITEM spawns item, ENTITY spawns entity,POTION adds potion effect to the triggerer
&lt;data> Argument depends on &lt;type>. ITEM = ItemType, ENTITY = EntityType, POTION = PotionEffectType
[-a &lt;amplifier>] Argument depends on &lt;type>. ITEM = quantity, ENTITY = quantity, POTION = duration
[-c] Specifies to cancel any events related with this block

**Comment by ziceptor** [comment]
@trentech  Error Video https://cloud.mail.ru/public/4Mbz/nKQ6VBsxi
